/****************************************************************************
 * boards/risc-v/erbium/minion/scripts/ld.script
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

EXTERN(__start)
ENTRY(__start)

PHDRS
{
	text PT_LOAD FLAGS(7);
}

SECTIONS
{
	/* The Erbium simulator reserves the first 512 bytes of MRAM. */
	. = 0x40000200;

	.rom_start : {
		_stext = .;
		KEEP(*(.text.__start))
	} :text

	. = ALIGN(4096);

	.exceptions : {
		KEEP(*(.text.exceptions))
	} :text

	.text : {
		*(.text.erbium_entry)
		*(.text)
		*(.text.*)
		*(.gnu.warning)
		*(.stub)
		*(.gnu.linkonce.t.*)
		*(.init)
		*(.fini)
		_etext = .;
	} :text

	.rodata : {
		_srodata = .;
		*(.rodata)
		*(.rodata.*)
		*(.gnu.linkonce.r*)
		_erodata = .;
	} :text

	.tdata : {
		_stdata = ABSOLUTE(.);
		*(.tdata .tdata.* .gnu.linkonce.td.*);
		_etdata = ABSOLUTE(.);
	} :text

	.tbss : {
		_stbss = ABSOLUTE(.);
		*(.tbss .tbss.* .gnu.linkonce.tb.* .tcommon);
		_etbss = ABSOLUTE(.);
	} :text

	_eronly = ABSOLUTE(.);

	.data : {
		_sdata = .;
		*(.data)
		*(.data.*)
		*(.gnu.linkonce.d*)
		. = ALIGN(8);
		_edata = .;
	} :text

	.ctors : {
		_sctors = .;
		*(.ctors)
		*(.init_array)
		_ectors = .;
	} :text

	.dtors : {
		_sdtors = .;
		*(.dtors)
		*(.fini_array)
		_edtors = .;
	} :text

	.bss : {
		_sbss = .;
		*(.bss)
		*(.bss.*)
		*(.sbss)
		*(.sbss.*)
		*(.gnu.linkonce.b*)
		*(COMMON)
		. = ALIGN(8);
		_ebss = .;
	} :text

	.stab 0 : { *(.stab) }
	.stabstr 0 : { *(.stabstr) }
	.comment 0 : { *(.comment) }
	.debug_abbrev 0 : { *(.debug_abbrev) }
	.debug_info 0 : { *(.debug_info) }
	.debug_line 0 : { *(.debug_line) }
	.debug_aranges 0 : { *(.debug_aranges) }
}
